pulibrary/pul_solr

- .gitignore
- solr_configs/pulmap/conf/mapping-ISOLatin1Accent.txt
- solr_configs/pulmap/conf/protwords.txt
- solr_configs/pulmap/conf/schema.xml
- solr_configs/pulmap/conf/solrconfig.xml
- solr_configs/pulmap/conf/spellings.txt
- solr_configs/pulmap/conf/stopwords.txt
- solr_configs/pulmap/conf/stopwords_en.txt
- solr_configs/pulmap/conf/synonyms.txt
- solr_configs/pulmap/core.properties
> adds solr config for pulmap

- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight/conf/solrconfig.xml
I forgot to make a pull request on this! The "more in this series" links and author/added title fields will be fixed by this update.
> update schema field config

- solr_configs/orangelight/conf/protwords.txt
- solr_configs/orangelight/conf/schema.xml
- spec/fixtures/1261826.json
- spec/fixtures/2393109.json
- spec/orangelight/protected_words_spec.rb
Add words to protected word file. Disables stemming for specific words. Closes pulibrary/orangelight#631.
> Add words to protected word file

- config/deploy/staging.rb
> lib-solr1 deploy config

- solr_configs/orangelight/conf/protwords.txt
> disable stemming for overseer and oversize

- Gemfile
- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight/conf/solrconfig.xml
- spec/fixtures/9774575.json
- spec/fixtures/9805613.json
- spec/orangelight/keyword_relevancy_spec.rb
- spec/orangelight/title_search_spec.rb
- spec/spec_helper.rb
Closes https://github.com/pulibrary/orangelight/issues/367
> Boost exact-ish phrase title matches.

- solr_configs/pulmap/conf/solrconfig.xml
> adds solr fields for title, publisher, and subject

- Rakefile
- solr_configs/orangelight/conf/schema.xml
Advances pulibrary/orangelight#859
> make publisher a searchable text field

- solr_configs/orangelight/conf/schema.xml
> Ensures that whitespace characters are not replaced for the title_l `fieldType`

- solr_configs/orangelight/conf/schema.xml
> Adds `title_p_index` as left-anchored search fields

- solr_configs/orangelight_staging/conf/schema.xml
Fully resolves #50 by keeping orangelight and orangelight_staging in sync.
> Copies the Solr config. for orangelight_staging

- solr_configs/orangelight/conf/solrconfig.xml
- solr_configs/orangelight_staging/conf/solrconfig.xml
- spec/fixtures/1225884.json
- spec/fixtures/1225885.json
- spec/fixtures/SCSB-3330744.json
- spec/orangelight/keyword_relevancy_spec.rb
refs pulibrary/orangelight#992
> Add global 'plus 50' boost to items with numeric ids

- solr_configs/orangelight/conf/solrconfig.xml
- solr_configs/orangelight_staging/conf/solrconfig.xml
Closes pulibrary/orangelight#1158.
> set up solr to backup after optimizing index, keep 1 backup

- solr_configs/pulmap/conf/solrconfig.xml
Removes healthcheckFile requirement.
> Update health check for pulmap solr config

- solr_configs/pulmap/conf/solrconfig_replication.xml
> Remove health check file from pulmap solrconfig_replication

- .gitignore
- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight_staging/conf/schema.xml
- spec/orangelight/title_search_spec.rb
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
> title_l search- Escape colon. Escape dash and space in a word

- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight/conf/solrconfig.xml
- solr_configs/orangelight/conf/solrconfig_replication.xml
- spec/orangelight/subject_search_spec.rb
Modifies subject fields to be unstemmed. Removed unused subject fields.
Also removes unused opensearch_display field.
> modify subject field to only allow unstemmed matches

- solr_configs/dpul-blacklight/conf/solrconfig_replication.xml
- solr_configs/figgy/conf/solrconfig_replication.xml
- solr_configs/lae-blacklight/conf/solrconfig_replication.xml
- solr_configs/pulmap/conf/solrconfig_replication.xml
Should help with system stability
> make polling interval for replication 4 minutes across all projects

- solr_configs/lae-blacklight/conf/schema.xml
- solr_configs/lae-blacklight/conf/solrconfig.xml
- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight/conf/solrconfig.xml
Adds solr cloud config for orangelight and the _version_ for the lae-blacklight project.
> adds solrcloud config to orangelight

- solr_configs/lae-blacklight/conf/schema.xml
Updating Solr config based on changes in https://github.com/pulibrary/lae-blacklight/pull/246
> Adding provenance field

- solr_configs/pulmap/conf/schema.xml
- spec/fixtures/princeton-4j03d346d.json
- spec/pulmap/diacritics_spec.rb
> Add ICUFoldingFilterFactory to Pulmap schema

- README.md
- solr_configs/solr.xml
> Add comments about the solr.xml in this repo, pointer to production file

- README.md
- config/deploy.rb
- config/deploy/solr2.rb
- config/deploy/solr3.rb
This only needs to happen on one box so I made solr1 the only member of
the `main` group.
fixes #104
> Update deploy to set the new configs and reload collections

- solr_configs/orangelight/conf/schema.xml
- solr_configs/orangelight/conf/solrconfig.xml
> Removes suggestions

- solr_configs/catalog-staging/conf/schema.xml
- solr_configs/catalog-staging/conf/solrconfig.xml
> Remove spellcheck from catalog-staging solr config

- config/deploy.rb
reload collections separately
completes work started with #113
fixes #104
> Copy config files to config sets, not collections

- solr_configs/catalog-staging/conf/schema.xml
To match [catalog-production](https://github.com/pulibrary/pul_solr/pull/122/files#diff-0813ca7bb856f1ddb8879cfd46efa939L411)
> remove textsuggest field from catalog-staging

- Capfile
- config/deploy.rb
>  Add cap tasks to list aliases and swap catalog aliases

- solr_configs/figgy/conf/schema.xml
Please see https://github.com/pulibrary/figgy/pull/1985#issuecomment-433527623 and https://github.com/pulibrary/figgy/issues/1883
> Adds a solr.TextField for case insensitive text searches for the Figgy Solr configuration

- .gitignore
- config/deploy.rb
- solr_configs/pulfa3/conf/_rest_managed.json
- solr_configs/pulfa3/conf/admin-extra.html
- solr_configs/pulfa3/conf/elevate.xml
- solr_configs/pulfa3/conf/mapping-ISOLatin1Accent.txt
- solr_configs/pulfa3/conf/protwords.txt
- solr_configs/pulfa3/conf/schema.xml
- solr_configs/pulfa3/conf/scripts.conf
- solr_configs/pulfa3/conf/solrconfig.xml
- solr_configs/pulfa3/conf/spellings.txt
- solr_configs/pulfa3/conf/stopwords.txt
- solr_configs/pulfa3/conf/stopwords_en.txt
- solr_configs/pulfa3/conf/synonyms.txt
- solr_configs/pulfa3/conf/xslt/example.xsl
- solr_configs/pulfa3/conf/xslt/example_atom.xsl
- solr_configs/pulfa3/conf/xslt/example_rss.xsl
- solr_configs/pulfa3/conf/xslt/luke.xsl
- solr_configs/pulfa3/core.properties
This will be necessary in order to deploy the ArcLight implementation of PULFA 3.0 into the staging environment for testing
> Adding the Solr configuration for PULFA 3.0/ArcLight deployments

- solr_configs/pulmap/conf/solrconfig.xml
> Set Pulmap autoCommit to 60 minutes

- solr_configs/pulmap/conf/schema.xml
> Update pulmap schema to add bbox type

- .gitignore
- solr_configs/catalog-production/conf/solrconfig.xml
- solr_configs/catalog-staging/conf/solrconfig.xml
- spec/orangelight/hash_id_spec.rb
Advances pulibrary/orangelight#1886.
> update orangelight solr config to support sitemap hashed id field

- solr_configs/catalog-production/conf/solrconfig.xml
This will bring cache sizes down to half of heap size
closes #168
> Reduce all OL cache numbers by factor of 4

- config/deploy.rb
> Add -z flag to upconfig to fix deploy

- solr_configs/catalog-staging/conf/solrconfig.xml
> Reduce cache sizes on catalog staging to match production

- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
Co-authored-by: Anna Headley <anna.headley@gmail.com>
> we need different values for zookeeper in staging

- .gitignore
- config/deploy/staging.rb
- solr_configs/reserves/conf/protwords.txt
- solr_configs/reserves/conf/schema.xml
- solr_configs/reserves/conf/solrconfig.xml
- solr_configs/reserves/conf/spellings.txt
- solr_configs/reserves/conf/stopwords.txt
- solr_configs/reserves/conf/stopwords_en.txt
- solr_configs/reserves/conf/synonyms.txt
- solr_configs/reserves/core.properties
> 203 reserves dss configs

- config/deploy/solr8-staging.rb
This will ease the deployment and management of Solr Collections for PULFALight.
> Ensuring that the pulfalight-staging Collection is refreshed consistently upon deployment

- solr_configs/pulmap/conf/schema.xml
>  Update Pulmap copyField statements for catch all search field

- config/deploy/solr8-production.rb
Progresses https://github.com/pulibrary/cicognara-rails/issues/474
> Add Solr 8 Core for Cicognara.

- config/deploy.rb
- config/deploy/solr8-production.rb
- solr_configs/pulfalight-production/conf/_rest_managed.json
- solr_configs/pulfalight-production/conf/admin-extra.html
- solr_configs/pulfalight-production/conf/elevate.xml
- solr_configs/pulfalight-production/conf/mapping-ISOLatin1Accent.txt
- solr_configs/pulfalight-production/conf/protwords.txt
- solr_configs/pulfalight-production/conf/schema.xml
- solr_configs/pulfalight-production/conf/scripts.conf
- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-production/conf/spellings.txt
- solr_configs/pulfalight-production/conf/stopwords.txt
- solr_configs/pulfalight-production/conf/stopwords_en.txt
- solr_configs/pulfalight-production/conf/synonyms.txt
- solr_configs/pulfalight-production/conf/xslt/example.xsl
- solr_configs/pulfalight-production/conf/xslt/example_atom.xsl
- solr_configs/pulfalight-production/conf/xslt/example_rss.xsl
- solr_configs/pulfalight-production/conf/xslt/luke.xsl
- solr_configs/pulfalight-production/core.properties
This also gets rid of the upload configset action and adds some description to the update task to make it clear that it also will create one if one doesn't exist.
> [Pulfalight] Production Configuration

- Capfile
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- config/collections.yml
- config/deploy.rb
- config/deploy/solr8-production.rb
- config/deploy/solr8-staging.rb
- config/schedule.rb
- lib/pul_solr.rb
- lib/pul_solr/backup_manager.rb
- lib/tasks/pul_solr.rake
- spec/pul_solr/backup_manager_spec.rb
- spec/pul_solr_spec.rb
- spec/spec_helper.rb
required refactoring some configuration out of capistrano
refs #215
Doesn't close that issue yet; still need to provision the prod solr box with ruby
> Add BackupManager and rake task to run collection backups

- config/deploy/solr8-staging.rb
- solr_configs/catalog-staging/conf/solrconfig.xml
- solr_configs/cicognara/conf/solrconfig.xml
Fixes #251
Also fixes deploy for staging; catalog-alma-qa should not have an entry in the config_map list since it uses the catalog_staging configset.
> Configure an update log for cicognara

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
Improves relevant search results.
Paired with https://github.com/pulibrary/pulfalight/pull/620
> [PULFALIGHT] Increase "mm", add location_info

- solr_configs/catalog-production-alt/conf/solrconfig.xml
- solr_configs/catalog-production/conf/solrconfig.xml
Applies settings recently fixed in catalog-staging (see https://github.com/pulibrary/pul_solr/pull/253) to catalog-production and catalog-production-alt configs.
Addresses https://github.com/pulibrary/marc_liberation/issues/1019
> Uses correct syntax in fq parameter(production)

- solr_configs/pulmap/conf/schema.xml
> Add all subjects field to pulmap solr config

- config/collections.yml
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/solr8-production.rb
- config/deploy/solr8-staging.rb
- config/deploy/staging.rb
- config/schedule.rb
- lib/pul_solr/backup_manager.rb
- lib/tasks/pul_solr.rake
- spec/pul_solr/backup_manager_spec.rb
> Add a backup subdirectory to separate backups by host

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
Companion to https://github.com/pulibrary/pulfalight/pull/768
> [PULFALIGHT] Add searching of citations.

- solr_configs/pulfalight-production/conf/schema.xml
- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/schema.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
Also generally synchronizes the config with Pulfalight.
Companion to https://github.com/pulibrary/pulfalight/pull/790
> [PULFALIGHT] Adds english processing of text

- solr_configs/catalog-production-alt/conf/solrconfig.xml
- solr_configs/catalog-production/conf/solrconfig.xml
- solr_configs/catalog-staging/conf/solrconfig.xml
Necessary for https://github.com/pulibrary/orangelight/pull/2393
> [Orangelight] Add electronic_portfolio_s to fl

- config/deploy.rb
To allow swapping aliases with different names
> Add optional flags to the alias:catalog cap task

- config/collections.yml
Two collections, two aliases, all pointing to catalog-production-v2 config
set.
Collections: catalog-alma-production1/catalog-alma-production2
Aliases: catalog-alma-production, catalog-alma-rebuild
> Add catalog-alma-production cores.

- solr_configs/catalog-production-v2/conf/solrconfig.xml
- solr_configs/catalog-staging/conf/solrconfig.xml
> Add autocommit to orangelight configs

- config/collections.yml
cross-referenced with solrcloud admin UI
> Update list of collections

- config/deploy/solr8-staging.rb
- config/deploy/staging.rb
Connected to https://github.com/pulibrary/dpul/issues/822
> Move dpul-staging solr8

- config/collections.yml
- config/deploy/solr8-production.rb
- config/deploy/solr8-staging.rb
- solr_configs/oawaiver/conf/_rest_managed.json
- solr_configs/oawaiver/conf/admin-extra.html
- solr_configs/oawaiver/conf/elevate.xml
- solr_configs/oawaiver/conf/mapping-ISOLatin1Accent.txt
- solr_configs/oawaiver/conf/protwords.txt
- solr_configs/oawaiver/conf/schema.xml
- solr_configs/oawaiver/conf/scripts.conf
- solr_configs/oawaiver/conf/solrconfig.xml
- solr_configs/oawaiver/conf/spellings.txt
- solr_configs/oawaiver/conf/stopwords.txt
- solr_configs/oawaiver/conf/synonyms.txt
Resolves https://github.com/pulibrary/oawaiver/issues/25
> Providing the Collection entries and configurations for oawaiver-staging and oawaiver-production

- solr_configs/catalog-production-v2/conf/solrconfig.xml
- solr_configs/catalog-staging/conf/solrconfig.xml
- spec/orangelight/hash_id_spec.rb
These changes improve indexing time significantly and we don't have
metrics to show that they were helping query times.
> [Catalog] Remove MaxDocs/Dedupe/Manual Cache Warming

- LICENSE
- README.md
- docker/Dockerfile
- docker/ci-start.sh
- docker/lando-start.sh
- docker/security.json
Moves Solr docker configs over from https://github.com/pulibrary/ci-solr-docker
Closes #290
> Add Solr docker config

- README.md
- config/collections.yml
Adds pulmap to solr8 collections and updates README with current commands.
> Migrate pulmap to solr8

- solr_configs/cicognara/conf/solrconfig.xml
Adds new field to Cicognara config file 
Mimics changes made to `solrconfig.xml` in PR https://github.com/pulibrary/cicognara-rails/pull/499
> Adds new field needed on search results for the thumbnail.

- config/deploy/solr8-staging.rb
The figgy config set is just called "figgy" for both staging and prod
closes #301
> Use the correct name for the figgy config set

- config/collections.yml
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/solr8-production.rb
- config/deploy/solr8-staging.rb
- Fix solr 7 collection config
- Use dpul as config set name in staging
- Add dpul config set to solr8-production
- Add dpul-production collection on solr8-production
> Add dpul-production collection on solr8-production

- solr_configs/pulmap/conf/solrconfig.xml
> Replace FastLRUCache in Pulmap solrconfig

- config/deploy/solr8-production.rb
- config/deploy/solr8-staging.rb
Failed deploy with missing configs in the list
https://gist.github.com/875403e25f181967c1daeaca9e0d6c6b
> Removing unused configsets

- config/collections.yml
Also remove the special collections index from solr7
> Adding the library and SC indexes to solr8 collections

- config/collections.yml
This contains DSS changes all the way through production and the updates to the catalog so far...
> Update the collections to reflect the current solr collections

- README.md
If we want the minimum replication factor to be two, this should really be noted in the instructions for creating new collections.  If you do not select it at creation you need to create a new index...
ref #199
> Adding note for replication factor

- solr_configs/pdc-discovery/conf/schema.xml
- solr_configs/pdc-discovery/conf/solrconfig.xml
Need to deploy changes made in https://github.com/pulibrary/pdc_discovery/issues/70
> Updated Solr configuration with new fields.

- solr_configs/pdc-discovery/conf/schema.xml
- solr_configs/pdc-discovery/conf/solrconfig.xml
Removing unused configuration
Updating lucene compatibility to match Solr 8
Work toward https://github.com/pulibrary/pdc_discovery/issues/72
> Update pdc_discovery solrconfig

- solr_configs/pdc-discovery/conf/solrconfig.xml
Work toward https://github.com/pulibrary/pdc_discovery/issues/72
> Enable id hash for pdc_discovery to support sitemap generation

- solr_configs/pulfalight-production/conf/schema.xml
- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/schema.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
> [pulfalight] Boost component results whose collection title matches query

- solr_configs/pdc-discovery/conf/schema.xml
- solr_configs/pdc-discovery/conf/synonyms.txt
Allows for Dan and Danny to be Synonyms for Daniel in the Author field
related PR in pcd-describe https://github.com/pulibrary/pul_solr/pull/335
> Adding updates to the PDC Discovery

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
Support for pulibrary/pulfalight#1086
> [Pulfalight] Add creator_tesim to qf

- solr_configs/pulmap/conf/schema.xml
> pulmap 1028 layer_geom_type

- solr_configs/catalog-production-v2/conf/solrconfig.xml
> [catalog] add local subject headings to solrconfig

- solr_configs/catalog-production-v2/conf/solrconfig.xml
- Follows pattern of other local subject vocabularies
Closes #340
> Add homoit_subject_unstem_search

- solr_configs/pulfalight-production/conf/schema.xml
- solr_configs/pulfalight-staging/conf/schema.xml
> Add new highlight text field and archaic_access_subjects

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
> Add has_direct_online_content_ssim to pulfalight search handler fl field

- solr_configs/pulfalight-production/conf/schema.xml
- solr_configs/pulfalight-staging/conf/schema.xml
> Add dynamic tsm configuration to Pulfalight

- Gemfile
- Gemfile.lock
Co-authored-by: Anna Headley <hackartisan@users.noreply.github.com>
Co-authored-by: Carolyn Cole <carolyncole@users.noreply.github.com>
> add new gems for ed25519 ssh key

- solr_configs/catalog-production-v2/conf/solrconfig.xml
Closes #361 
Made a best guess for boosting - don't want to boost too much, since this is an uncontrolled field.
> Add uncontrolled_keyword_unstem_search to keyword search

- solr_configs/catalog-production-v2/conf/solrconfig.xml
Connected to https://github.com/pulibrary/orangelight/issues/3603
> Increase documentCache size for the Catalog

- config/collections.yml
Collection already created manually in solr admin panel
refs pulibrary/pulfalight#1252
> Add pulfalight-qa collection

- solr_configs/catalog-production-v2/conf/schema.xml
- solr_configs/catalog-production-v2/conf/solrconfig.xml
> [Catalog] Remove unneeded comments from solr config

- solr_configs/catalog-production-v2/conf/solrconfig.xml
Adding an example request handler with a boost that makes engineering documents come first
refs https://github.com/pulibrary/orangelight/issues/3816
> [ORANGELIGHT] Adding a new example requestHandler for algorithm switching

- solr_configs/catalog-production-v2/conf/solrconfig.xml
- spec/orangelight/highlighting_spec.rb
part of https://github.com/pulibrary/orangelight/issues/3795
> Adds HighlightComponent, part of #3795

- solr_configs/catalog-production-v2/conf/schema.xml
- solr_configs/catalog-production-v2/conf/solrconfig.xml
- spec/orangelight/highlighting_spec.rb
part of #3797
Adds subject fields in highlighting section
> 3797 subject fields

- solr_configs/catalog-production-v2/conf/schema.xml
- solr_configs/catalog-production-v2/conf/solrconfig.xml
- spec/orangelight/highlighting_spec.rb
part of https://github.com/pulibrary/orangelight/issues/3797
> Add highlighting in notes_display

- solr_configs/catalog-production-v2/conf/solrconfig.xml
- spec/fixtures/99125315781206421.json
- spec/fixtures/99129071662406421.json
- spec/orangelight/highlighting_spec.rb
closes https://github.com/pulibrary/pul_solr/issues/383
> Use hl.usePhraseHighlighter: false to highlight all the matching terms - not just the whole phrase

- lib/pul_solr.rb
- spec/pulmap/diacritics_spec.rb
- spec/spec_helper.rb
> Clean up config a little bit

- .circleci/config.yml
- README.md
- config/deploy/staging_new.rb
refs https://github.com/pulibrary/princeton_ansible/issues/4666
> Adding a capistrano configuration for the new solr staging

- .circleci/config.yml
- .tool-versions
- Gemfile.lock
This is the ruby version on the new staging servers. It's in draft because I'm not sure if we need to wait on the prod servers to merge it.
closes #378
> Use ruby 3

- README.md
I spent some time trying to edit the memory settings in the downloaded, rather than the installed Memory Analyzer package, which did not work. 😂
> [heap dump docs] Clarify where to find the Memory Analyzer to change memory settings

- Gemfile
- config/deploy/staging.rb
- lib/pul_solr.rb
> Get solr backups running again on staging

- README.md
Also, add a note about the async param for large solr collections
Connected to https://github.com/pulibrary/orangelight/issues/3476
> [backup docs] Add more details about how to find the params for restoring a backup

- README.md
- config/collections.yml
- config/deploy/solr9_production.rb
- config/deploy/solr9_staging.rb
- lib/tasks/pul_solr.rake
this configures our solr9 configuration. The deploy user will now be
able to run backups on the defined solr boxes
closes #411
> add solr9 configurations

- README.md
Thanks to @christinach for identifying this issue!
Related to https://github.com/pulibrary/orangelight/issues/3476
> [restore docs] Make sure you have enough space on disk for the backup you want to restore

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
Closes pulibrary/pulfalight#1153
> Fixes breadcrumbs for Pulfalight.

- solr_configs/dpulc-staging/conf/schema.xml
- solr_configs/dpulc-staging/conf/solrconfig.xml
- solr_configs/dpulc-staging/core.properties
Companion to https://github.com/pulibrary/dpul-collections/pull/116
> [DPULC] Add language detection support.

- solr_configs/dpulc-staging/conf/schema.xml
- solr_configs/dpulc-staging/conf/solrconfig.xml
> Update dpulc solr config

- solr_configs/dpulc-staging/conf/schema.xml
- solr_configs/dpulc-staging/conf/solrconfig.xml
Companion to pulibrary/dpul-collections#151
> [DPUL-C] Title copying & language detection

- solr_configs/dpulc-staging/conf/schema.xml
- solr_configs/dpulc-staging/conf/solrconfig.xml
refs pulibrary/dpul-collections#237
> [dpul-collections] Add stemmed titles and descriptions to default qf

- solr_configs/dpulc-staging/conf/slug.js
See https://github.com/pulibrary/dpul-collections/pull/251
Creates correct item slugs for languages with RTL script:
> Improve dpulc slug generation

- solr_configs/dpulc-staging/conf/schema.xml
advances pulibrary/dpul-collections#272
> [dpul-collections] Sort nil dates last in both directions

- solr_configs/pulfalight-production/conf/solrconfig.xml
- solr_configs/pulfalight-staging/conf/solrconfig.xml
refs pulibrary/pulfalight#1447
> [pulfalight] Add access_ssi to default field list

- config/deploy.rb
- config/deploy/solr9_production.rb
- config/deploy/solr9_staging.rb
> Make configuration copying / loading a no-op for cdh-only context

- .circleci/config.yml
- .tool-versions
- Gemfile
- Gemfile.lock
- README.md
- lib/pul_solr/backup_manager.rb
- spec/pul_solr/backup_manager_spec.rb
- spec/spec_helper.rb
> Upgrade ruby version

- solr_configs/catalog-production-v2/conf/schema.xml
homoit_subject_facet, local_subject_facet
Helps with https://github.com/pulibrary/orangelight/pull/3386
> Add lc_subject_facet, lcgft_genre_facet, aat_genre_facet, rbgenr_genre_facet, homoit_genre_facet

- solr_configs/catalog-production-v2/conf/schema.xml
> save the new facet fields so that we can see them in the json

- solr_configs/catalog-production-v2/conf/schema.xml
Helps with https://github.com/pulibrary/orangelight/pull/3386
> Add fast_subject_facet field

- solr_configs/dss-production/conf/schema.xml
- solr_configs/dss-production/conf/solrconfig.xml
> [DSS] Remove more unused fields

- solr_configs/dss-production/conf/schema.xml
Closes #420 
Stakeholder tested the new default similarity factory on staging and signed off.
> [DSS] Remove legacy similarity factory

- config/deploy/production.rb
- config/deploy/solr9_production.rb
- config/deploy/solr9_staging.rb
- config/deploy/staging.rb
> Update capistrano to include .princeton.edu

- solr_configs/dpulc-staging/conf/solrconfig.xml
Work towards pulibrary/dpul-collections#394
> [DPUL-C] Remove query parameters that were breaking recommended items.

- solr_configs/dpulc-staging/conf/solrconfig.xml
Work towards pulibrary/dpul-collections#533
> [DPUL-C] Search more fields for dpul-c.

- .circleci/config.yml
- spec/dss/keyword_search_spec.rb
- spec/dss/subject_search_spec.rb
- spec/dss/title_search_spec.rb
- spec/orangelight/advanced_search_spec.rb
- spec/orangelight/apostrophe_spec.rb
- spec/orangelight/author_search_spec.rb
- spec/orangelight/cjk_mapping_spec.rb
- spec/orangelight/default_fields_spec.rb
- spec/orangelight/hash_id_spec.rb
- spec/orangelight/in_series_search_spec.rb
- spec/orangelight/keyword_relevancy_spec.rb
- spec/orangelight/notes_search_spec.rb
- spec/orangelight/protected_words_spec.rb
- spec/orangelight/publisher_search_spec.rb
- spec/orangelight/punctuation_tokens_spec.rb
- spec/orangelight/series_title_index_search_spec.rb
- spec/orangelight/standard_no_spec.rb
- spec/orangelight/subject_search_spec.rb
- spec/orangelight/title_search_spec.rb
- spec/pulmap/diacritics_spec.rb
- spec/spec_helper.rb
> Use shared examples to run tests in both solr 8 an 9

- solr_configs/dpulc-production/conf/schema.xml
- solr_configs/dpulc-production/conf/solrconfig.xml
- solr_configs/dpulc-staging/conf/schema.xml
- solr_configs/dpulc-staging/conf/solrconfig.xml
Companion to  pulibrary/dpul-collections#784
Merge this when that's merged.
> [DPUL-C] Fix searching metadata in DPUL-C.
