configs/orangelight/conf/schema.xml
configs/orangelight/conf/solrconfig.xml
spec/fixtures/1332805.json
spec/fixtures/454035.json
spec/fixtures/484612.json
spec/fixtures/5188770.json
spec/fixtures/7419275.json
spec/orangelight/author_search_spec.rb
spec/orangelight/subject_search_spec.rb

Indexed subject and author fields as text fields, which support diacritics folding. Closes pulibrary/orangelight#515 and closes pulibrary/orangelight#249.
The text field also doesn't use the stopword filter (before only queries that excluded the stop word would match). Closes pulibrary/orangelight#505

subject and author indexed as text field

---

spec/orangelight/apostrophe_spec.rb
spec/orangelight/author_search_spec.rb
spec/orangelight/cjk_mapping_spec.rb
spec/orangelight/keyword_relevancy_spec.rb
spec/orangelight/protected_words_spec.rb
spec/orangelight/punctuation_tokens_spec.rb
spec/orangelight/standard_no_spec.rb
spec/orangelight/subject_search_spec.rb
spec/orangelight/title_search_spec.rb
spec/spec_helper.rb

Hi! We at Penn enjoyed the impromptu presentation on this repo by @tampakis at the Blacklight Summit last week. We're currently trying to build on your excellent work for our own Solr schemas, and ran into the issue of not being to access different Solr cores/instances because of the way spec_helper.rb was written. 
This is a simple refactor to allow you to override the default Solr instance used. Here's some sample code that uses it:
```ruby
require 'spec_helper'
require 'json'
describe 'sample tests' do
include_context 'solr_helpers'
before(:all) do
solr(core: "solr/pulmap")
delete_all
end
describe 'sample field' do
it 'does something appropriate' do
expect(solr_resp_doc_ids_only(...)).to include(...)
end
end
after(:all) do
delete_all
end
end
```
Just sending this PR along in the spirit …

use shared_context to allow contexts to access diff solr cores and instances

---

Gemfile
Rakefile
solr_configs/orangelight/conf/schema.xml
solr_configs/orangelight/conf/solrconfig.xml
spec/orangelight/keyword_relevancy_spec.rb

Advances #29. Removes bigram filter in exact search field type and boosts left anchor in keyword search.

remove bigram filter in exact search field

---

config/deploy.rb

Instead of restarting the Solr service, reload the Solr cores after deploy so the solr config changes can take effect.

reload cores on deploy

---

solr_configs/orangelight/conf/schema.xml
spec/orangelight/title_search_spec.rb

Resolves #50 and https://github.com/pulibrary/orangelight/issues/1101

Ensures that whitespace padding punctuation marks ar ensuring that whitespace padding punctuation marks are filtered during indexing and querying

---

solr_configs/orangelight/conf/protwords.txt
solr_configs/orangelight_staging/conf/protwords.txt

Preventing 'musicals' from being stemmed to 'music' or 'musical'

---

solr_configs/orangelight/conf/schema.xml
solr_configs/orangelight_staging/conf/schema.xml

Properly resolves https://github.com/pulibrary/orangelight/issues/1184
This was originally provided by @tampakis in https://github.com/pulibrary/pul_solr/pull/57#issuecomment-373471534

Ensuring that the default values for @preserveOriginal and @stemEnglishPossessive are overridden for WordDelimiterGraphFilterFactory

---

solr_configs/lae-blacklight/conf/solrconfig_replication.xml

Updates version number to 7.0.0 in solrconfig_replication to match version number in solrconfig for lae-blacklight.

Updates version number to 7.0.0 in solrconfig_replication for lae

---

solr_configs/orangelight/conf/schema.xml
spec/orangelight/apostrophe_spec.rb
spec/orangelight/title_search_spec.rb

Reimplements left-anchor search field to avoid using n-grams. The search expects wildcard to be added to the end of the query, which will be sent from the catalog app. In changing the config, also resolves an issue where non left-anchor searches would match (queries that don't include the first word of the title but includes a substring of the title).
The new implementation decreases the size of the index by about 40% which should lessen memory needs for solr.

reimplements left-anchor search to avoid n-grams

---

solr_configs/orangelight/conf/schema.xml
solr_configs/orangelight/conf/solrconfig.xml
solr_configs/orangelight/conf/solrconfig_replication.xml
spec/orangelight/cjk_mapping_spec.rb

Adds cjk mapping for notes, publisher, and series title search fields. Closes pulibrary/orangelight#1284.

Adds cjk mapping for advanced search fields

---

solr_configs/orangelight/conf/schema.xml
spec/orangelight/apostrophe_spec.rb

Advances #94. Allows article to be separated by whitespace from following word in keyword searches. However, the title starts with search still requires them together (l'opera would work but not l' opera).

tokenizes on apostrophes, preserves original

---

solr_configs/orangelight/conf/schema.xml
spec/orangelight/cjk_mapping_spec.rb

Removes copy fields. With https://github.com/pulibrary/marc_liberation/pull/441, the cjk_series_title and cjk_notes fields will be processed via Traject.

remove unused cjk copy fields

---

architecture-decisions/0001-document-architecture-decisions.md

Cribbed from https://github.com/MITLibraries/mario/tree/master/docs/architecture-decisions

Starting architecture decision records

---

README.md
config/deploy.rb
config/deploy/development.rb

These tasks enable one to readily upload, update, and delete Configsets along with creating and deleting Collections once `pul_solr` has been deployed to a server environment.  This also adds a development deployment environment for testing this using a Vagrant box.

Implements Configset and Collection management Capistrano tasks

---

config/deploy/production.rb

Remove figgy-production2 collection

---

solr_configs/catalog-production-alt/conf/schema.xml
solr_configs/catalog-production-alt/conf/solrconfig.xml
solr_configs/catalog-staging/conf/schema.xml
solr_configs/catalog-staging/conf/solrconfig.xml
spec/orangelight/subject_search_spec.rb

Makes genre terms searchable in unstem_search fields.
Supports separated siku and lc subject fields.
Updated version of https://github.com/pulibrary/pul_solr/pull/181

includes genre terms in subject keyword search

---

spec/pulfalight/identifier_spec.rb

this test reflected a search by component ID that had collection ID repeated twice, no needed.

remove unneeded tests for component ID

---

config/deploy/solr8-staging.rb

The collection was added via the solr admin panel. This ensures its config set
will be reloaded if it's changed

Add new collection catalog-alma-qa

---

solr_configs/pulfalight-staging/conf/schema.xml
solr_configs/pulfalight-staging/conf/solrconfig.xml

Work for https://github.com/pulibrary/pulfalight/issues/116
PF2/PS2 applies boosting based on two-word "shingles", which works perfectly for "Box 2" and "Folder 1", especially if we set the phrase slop to 0.

Pulfalight Box/Folder Search

---

solr_configs/catalog-staging/conf/solrconfig.xml

It uses the correct syntax to indicate a date range in the `<lst><str name="fq">cataloged_tdt...` settings.
The new syntax removes the Solr warning in the log referenced in https://github.com/pulibrary/marc_liberation/issues/1019.
This change needs to be merged before we can test https://github.com/pulibrary/marc_liberation/pull/1056

Uses the correct syntax in the fq parameter 

---

solr_configs/catalog-staging/conf/schema.xml
solr_configs/catalog-staging/conf/solrconfig.xml

Bring changes that had not been ported. 
Note that it **does not** bring the changes related to the use of Point fields instead of Trie fields.

Brings to staging changes from catalog-production-alt 

---

solr_configs/pulfalight-production/conf/solrconfig.xml
solr_configs/pulfalight-staging/conf/solrconfig.xml

This prioritizes a smaller result set, as per pulibrary/pulfalight#557

Set Pulfalight MM to 100%

---

solr_configs/pulfalight-production/conf/solrconfig.xml
solr_configs/pulfalight-staging/conf/solrconfig.xml

Removes phrase slop (which will weight closer phrases higher), boosts the right title field, and lowers the title boost so that the collection boost in Pulfalight will take priority.

[Pulfalight] Improve relevancy for title searches via keywords

---

solr_configs/catalog-production-v2/conf/solrconfig.xml
solr_configs/catalog-staging/conf/solrconfig.xml

Adds field `contained_in_s` needed to support showing holdings for bound-withs, see PR https://github.com/pulibrary/orangelight/pull/2553

Adds field to solrconfig.xml

---

README.md

without quotes you get errors like `zsh: no matches found: configset:delete[catalog-staging]`
with quotes the commands work...
```
[colec@ltopmaccole pul_solr (main)]$ bundle exec cap solr8-staging "configsets:delete[catalog-staging]"
00:00 configsets:delete
01 curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=catalog-staging&omitHeader=true"
01   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
01                                  Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:
01 --:--     0
100   632  100   632    0     0  13446      0 --:--:-- --:--:-- --:--:-- 13446
...
```

Add quotes around cap arguments with "["

---

README.md

`docker buildx build` is a good way to build this image so that it is compatible with arm64 (new Mac chips) and amd64 architectures.
Expected output when you build using this process:
- `docker inspect image IMAGE_TAG | grep -i architecture` should say amd64 on an Intel chip and arm64 on an M1 mac.
- `docker manifest inspect  IMAGE_TAG` should have entries for both amd64 and arm64.

Multi-arch docker build instructions

---

solr_configs/catalog-production-v2/conf/schema.xml
solr_configs/catalog-production-v2/conf/solrconfig.xml
spec/orangelight/hash_id_spec.rb

This brings back the hashed id field added in https://github.com/pulibrary/pul_solr/pull/161, also taking inspiration from https://github.com/pulibrary/pul_solr/pull/323
Merging this is a prerequisite to https://github.com/pulibrary/orangelight/issues/3166

Add hash to orangelight config for dynamic sitemaps

---

docker/security.json

- Bibdata indexing in CI was failing with the existing image
Connected to https://github.com/pulibrary/bibdata/issues/2161 - replace solr_wrapper for CI
With blockUnknown set to "true" traject was getting authentication errors each time it was trying to index to Solr. (see, e.g., [this CI run](https://app.circleci.com/pipelines/github/pulibrary/bibdata/3138/workflows/23dbea9d-02c2-439b-9967-d57fb985405f/jobs/13638) - when I re-ran with SSH and put a byebug in, the traject errors were because Solr was returning a 401 authentication error)

Change blockUnknown to false for CI

---

solr_configs/catalog-production-v2/conf/solrconfig.xml

This reverts commit 0a0e7ce39f0b626c5ec2c77c321fc3331a85c8c7.
It is unclear; however, this may be causing very slow garbage collection intermittently, and it is not clear that it is truly increasing performance (there seems to be a performance gain after every deploy, which can mask true performance gains); the DocumentCache hit ratio was still low at 0.22 even after this change.

Revert "Increase documentCache size for the Catalog"

---

solr_configs/catalog-production-v2/conf/schema.xml

Also, remove some unused fieldTypes that used the deprecated SynonymFilterFactory.
helps with https://github.com/pulibrary/orangelight/issues/3653

[catalog] Use SynonymGraphFilterFactory instead of deprecated SynonymFilterFactory

---

solr_configs/catalog-production-v2/conf/solrconfig.xml

Utilize init params to remove the redundancy in the search request handlers.  See
https://solr.apache.org/guide/solr/latest/configuration-guide/initparams.html for more information on init params in solr.

Refactors the requestHandlers to utilize init params

---

solr_configs/catalog-production-v2/conf/schema.xml

Resolves pulibrary/orangelight#3830
The field was not adding emphasis because the highlighting results require the field to be explicitly defined in the schema.xml
In the future we will need to make sure any fields we add to highlighting isn't a dynamically defined field.

Added author_display field explicitly

---

config/deploy/production.rb

We removed lib-solr-prod4, now we should use 7.
The rake tasks seem to work fine.
Closes #398

Use lib-solr-prod7 instead of lib-solr-prod4

---

config/deploy/production.rb

Related to https://github.com/pulibrary/princeton_ansible/issues/4858 and https://github.com/pulibrary/princeton_ansible/issues/4969.
We have upgraded the production zookeeper cluster to run on Ubuntu 22 (Jammy Jellyfish). This PR updates the production deployment to use the new infrastructure.

switches to new jammy VMs for prod zk cluster

---

README.md

Since these instructions were first written, we have [configured solr as a systemd service with `PrivateTmp=true`](https://github.com/pulibrary/princeton_ansible/pull/4874).  This is a good security protection to have, but it unfortunately also blocks the heap dump.
The nsenter command allows us to bypass this protection temporarily by entering the "namespace" of the solr process.
Also, format the steps as an ordered list.

[heap dump docs] Use nsenter to bypass systemd security protections

---

README.md

Solr uses 8983, not the goofy port number I used for my SSH tunnel.

[backup docs] Fix port number

---

lib/tasks/pul_solr.rake

closes #428 
pulling from local instead of github means
1. we can pull files over before merging, allowing you to open PRs in both repos at the same time
2. we can just copy everything recursively, without having to know what the filenames are

Add task to synchronize solr configs from local repos

---

solr_configs/catalog-production-v2/conf/solrconfig.xml
spec/orangelight/default_fields_spec.rb

Orangelight has a feature where users can text themselves the call number of an item. While working on pulibrary/orangelight#4479, we found that this feature wasn't working, because we never actually told solr that we want to get the call_number_display field.
This adds call_number_display to the fl list, so it is retrieved by default.

[catalog] Include call_number_display field in the default fl

---

config/deploy/solr9_production.rb
config/deploy/solr9_staging.rb

The CDH collections are live on Solr9 in both staging and production. This PR adds them to the `config_map` so those collections will get backed up by the rake task.

adds CDH Solr9 collections to backup rake task

---

config/schedule.rb
lib/pul_solr/backup_manager.rb
lib/tasks/pul_solr.rake

leaving this in draft to deploy to staging and let it run for a bit there.
refs #447

Split cleanups from backups, so the one doesn't hold up the other

---

Gemfile.lock

Recent versions of OSX require more stringent ssh algorithms. Without this upgrade users of MacOS 15.2+ will get this error: 
> Exception while executing as deploy@lib-solr-prod7: could not settle on encryption_client algorithm (SSHKit::Runner::ExecuteError)
Server encryption_client preferences: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
Client encryption_client preferences:
More details here: https://github.com/net-ssh/net-ssh/issues/956

Upgrade net-ssh to enable more stringent ssh algorithms

---

solr_configs/dss-production/conf/schema.xml
solr_configs/dss-production/conf/solrconfig.xml

Helps with #420, since it will be easier to balance the field weights without the config being filled with unused field weights

[dss] Remove several fields that are not used in DSS

---

solr_configs/catalog-production-v2/conf/schema.xml

[This was deprecated in Solr 7](https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-7.html#spatial-fields)!

[catalog] Remove deprecated LatLon field type

---

solr_configs/catalog-production-v2/conf/schema.xml

This allows the source language to be displayed in the show page and the raw JSON.
Helps with https://github.com/pulibrary/orangelight/issues/4634

[catalog] Add source language of translation field
